/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'total' : IDL.Nat,
  'timestamp' : IDL.Int,
  'discount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'editMenuItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'finalizeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Nat], [Order], []),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getDailySalesSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'itemCount' : IDL.Nat,
          'discount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDateWiseSalesHistory' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getItemWiseSales' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getMenuItemsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(MenuItem)))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'total' : IDL.Nat,
    'timestamp' : IDL.Int,
    'discount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'editMenuItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'finalizeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Nat], [Order], []),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getDailySalesSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'itemCount' : IDL.Nat,
            'discount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDateWiseSalesHistory' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getItemWiseSales' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getMenuItemsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(MenuItem)))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };