/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'category' : string,
  'price' : bigint,
}
export interface Order {
  'tax' : bigint,
  'total' : bigint,
  'timestamp' : bigint,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : bigint,
}
export interface _SERVICE {
  'addMenuItem' : ActorMethod<[string, bigint, string], bigint>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'editMenuItem' : ActorMethod<[bigint, string, bigint, string], undefined>,
  'finalizeOrder' : ActorMethod<[Array<OrderItem>], Order>,
  'getDailySalesSummary' : ActorMethod<
    [],
    { 'tax' : bigint, 'total' : bigint, 'itemCount' : bigint }
  >,
  'getDateWiseSalesHistory' : ActorMethod<[bigint, bigint], Array<Order>>,
  'getItemWiseSales' : ActorMethod<[], Array<[string, bigint, bigint]>>,
  'getMenuItemsByCategory' : ActorMethod<[], Array<[string, Array<MenuItem>]>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];